"""phase2_booking_provider_user_id

Revision ID: 45c2c0826484
Revises: 092f2a3b65d2
Create Date: 2026-08-03 16:17:59.781740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45c2c0826484'
down_revision: Union[str, None] = '092f2a3b65d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('provider_user_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('auto_release_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_bookings_auto_release_at'), 'bookings', ['auto_release_at'], unique=False)
    op.create_index(op.f('ix_bookings_provider_user_id'), 'bookings', ['provider_user_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'users', ['provider_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_provider_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_auto_release_at'), table_name='bookings')
    op.drop_column('bookings', 'auto_release_at')
    op.drop_column('bookings', 'provider_user_id')
    # ### end Alembic commands ###
