"""phase2_missing_features

Revision ID: a476b0903c41
Revises: 45c2c0826484
Create Date: 2026-08-03 17:57:29.448919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a476b0903c41'
down_revision: Union[str, None] = '45c2c0826484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('commission_tiers', sa.JSON(), nullable=True))
    op.add_column('offers', sa.Column('urgent_surcharge_pct', sa.Float(), nullable=True))
    op.add_column('reviews', sa.Column('quality_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('punctuality_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('communication_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'communication_rating')
    op.drop_column('reviews', 'punctuality_rating')
    op.drop_column('reviews', 'quality_rating')
    op.drop_column('offers', 'urgent_surcharge_pct')
    op.drop_column('categories', 'commission_tiers')
    # ### end Alembic commands ###
